import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar structure mirrors the three-door landing + five canonical docs + community.
// Route manifest routes: /manifest/ /cookbook/ /migrate/ /troubleshoot/ /deploy/ /abi/ /errors/<name>

const sidebars: SidebarsConfig = {
  docs: [
    // Three-door landing (from docs/maos.dev/)
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "index",
        "write-a-spirit",
        "run-maos",
        "understand-maos",
      ],
    },
    // Five canonical docs (AC-1 spine)
    {
      type: "category",
      label: "Manifest Schema",
      collapsed: true,
      link: { type: "generated-index", slug: "/manifest/latest" },
      items: [{ type: "autogenerated", dirName: "manifest" }],
    },
    {
      type: "category",
      label: "Cookbook",
      collapsed: true,
      link: { type: "doc", id: "cookbook/index" },
      items: [{ type: "autogenerated", dirName: "cookbook" }],
    },
    {
      type: "category",
      label: "Migration",
      collapsed: true,
      link: { type: "doc", id: "migrate/index" },
      items: [{ type: "autogenerated", dirName: "migrate" }],
    },
    {
      type: "category",
      label: "Troubleshoot",
      collapsed: true,
      link: { type: "doc", id: "troubleshoot/index" },
      items: [{ type: "autogenerated", dirName: "troubleshoot" }],
    },
    {
      type: "category",
      label: "Deploy",
      collapsed: true,
      link: { type: "doc", id: "deploy/index" },
      items: [{ type: "autogenerated", dirName: "deploy" }],
    },
    {
      type: "category",
      label: "ABI Reference",
      collapsed: true,
      link: { type: "generated-index", slug: "/abi/latest" },
      items: [{ type: "autogenerated", dirName: "abi" }],
    },
    // Community / Governance (AC-5)
    {
      type: "category",
      label: "Community",
      collapsed: true,
      items: [
        "community/governance",
        "community/code-of-conduct",
        "community/rfc-template",
        "community/locales",
        "community/trademark",
        "community/breaking-changes",
      ],
    },
  ],
};

export default sidebars;
