//! Build-time SHA-256 enforcement for pinned seed files.
//!
//! Computes the live SHA-256 of both seed TOMLs and compares against the
//! compile-time constants in `secret_redaction::SEED_FILE_SHA256` and
//! `red_team::SEED_FILE_SHA256`.  A mismatch emits a warning (the constants
//! are generated by `lib.rs` at compile-time and checked here).
//!
//! This is the shift-cost-to-authoring-time discipline: any seed edit
//! triggers a build warning naming exactly what to update.

use sha2::{Digest, Sha256};
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=seeds/secret-redaction-seeds-v0.1.toml");
    println!("cargo:rerun-if-changed=seeds/red-team-seeds-v0.1.toml");
    println!("cargo:rerun-if-changed=seeds/ccac-seeds-v1.0.toml");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = std::env::var("OUT_DIR").unwrap();

    // --- secret-redaction ---
    let sr_path = manifest_dir.join("seeds/secret-redaction-seeds-v0.1.toml");
    let sr_data = std::fs::read(&sr_path).expect("failed to read secret-redaction seeds");
    let sr_actual = hex::encode(Sha256::digest(&sr_data));
    let sr_pinned = "a9dce6273711e44ffc20157cd026dcc94fbfcb95bf1b8989a0e1451a62799aec";

    let sr_gen_path = PathBuf::from(&out_dir).join("sha_check_sr.rs");
    if sr_actual != sr_pinned {
        let msg = format!(
            "seed-file SHA mismatch: src/secret_redaction/mod.rs pins {} but \
             seeds/secret-redaction-seeds-v0.1.toml hashes to {} — update \
             SEED_FILE_SHA256, regenerate tests/corpora/secret-redaction-1e4.jsonl, \
             and update MANIFEST.toml",
            sr_pinned, sr_actual
        );
        std::fs::write(&sr_gen_path, format!("compile_error!(\"{}\");", msg)).unwrap();
        println!("cargo:warning={}", msg);
    } else {
        std::fs::write(&sr_gen_path, "const _SR_CHECK_OK: () = ();\n").unwrap();
    }

    // --- red-team ---
    let rt_path = manifest_dir.join("seeds/red-team-seeds-v0.1.toml");
    let rt_data = std::fs::read(&rt_path).expect("failed to read red-team seeds");
    let rt_actual = hex::encode(Sha256::digest(&rt_data));
    let rt_pinned = "f4a5988b2c622686e78c4c698ff0af575c766bbfa77f505d94b62d41fa742f2e";

    let rt_gen_path = PathBuf::from(&out_dir).join("sha_check_rt.rs");
    if rt_actual != rt_pinned {
        let msg = format!(
            "seed-file SHA mismatch: src/red_team/mod.rs pins {} but \
             seeds/red-team-seeds-v0.1.toml hashes to {} — update \
             SEED_FILE_SHA256, regenerate tests/corpora/red-team-640.jsonl, \
             and update MANIFEST.toml",
            rt_pinned, rt_actual
        );
        std::fs::write(&rt_gen_path, format!("compile_error!(\"{}\");", msg)).unwrap();
        println!("cargo:warning={}", msg);
    } else {
        std::fs::write(&rt_gen_path, "const _RT_CHECK_OK: () = ();\n").unwrap();
    }

    // --- ccac (Story 7.3) ---
    let ccac_path = manifest_dir.join("seeds/ccac-seeds-v1.0.toml");
    let ccac_data = std::fs::read(&ccac_path).expect("failed to read ccac seeds");
    let ccac_actual = hex::encode(Sha256::digest(&ccac_data));
    let ccac_pinned = "700d294661d0375138e84fe2f8e7ac50dd46172425f25f777a60445d529e28ee";

    let ccac_gen_path = PathBuf::from(&out_dir).join("sha_check_ccac.rs");
    if ccac_actual != ccac_pinned {
        let msg = format!(
            "seed-file SHA mismatch: src/ccac/mod.rs pins {} but \
             seeds/ccac-seeds-v1.0.toml hashes to {} — update \
             CCAC_SEED_FILE_SHA256, regenerate tests/corpora/ccac-v1.0-<sha>.jsonl, \
             and update MANIFEST.toml",
            ccac_pinned, ccac_actual
        );
        std::fs::write(&ccac_gen_path, format!("compile_error!(\"{}\");", msg)).unwrap();
        println!("cargo:warning={}", msg);
    } else {
        std::fs::write(&ccac_gen_path, "const _CCAC_CHECK_OK: () = ();\n").unwrap();
    }

    println!("cargo:rustc-cfg=sha_check_done");
}

mod hex {
    pub fn encode(data: impl AsRef<[u8]>) -> String {
        data.as_ref().iter().map(|b| format!("{:02x}", b)).collect()
    }
}
