//! MAOS parameterized corpus generators.
//!
//! This crate provides the [`CorpusGenerator`] trait — the binding API contract
//! for every deterministic corpus generator in the MAOS workspace — plus the two
//! generators shipped at v0.1-α:
//!
//! * [`secret_redaction`] — 10⁴-item per-commit secret-leakage corpus from 200
//!   SHA-pinned seed patterns across 11 named secret classes.
//! * [`red_team`] — ≥640-item adversarial-Spirit red-team corpus from 80
//!   canonical scenarios across 8 §8.1 attack classes.
//!
//! Future stories add `pub mod ccac;` (Story 7.3, v1.0) following the same
//! SHA-pinned seed + compile-time enforcement discipline.

use std::collections::BTreeMap;

// Build-time SHA-256 enforcement (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/sha_check_sr.rs"));
include!(concat!(env!("OUT_DIR"), "/sha_check_rt.rs"));

pub mod red_team;
pub mod secret_redaction;

// ---------------------------------------------------------------------------
// Binding types
// ---------------------------------------------------------------------------

/// Outcome of validating a single corpus item.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum ValidationOutcome {
    /// The item meets all validity criteria.
    Valid,
    /// The item fails one or more validity criteria.
    Invalid {
        /// Human-readable reason.
        reason: String,
    },
    /// The item would produce a **false negative** at gate time — a real-run
    /// counterpart could pass undetected.  This is the load-bearing P0
    /// detector for the secret-redaction generator.
    FalseNegativeRisk {
        /// Human-readable description of the risk.
        detail: String,
    },
}

/// Per-class coverage statistics.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ClassCoverage {
    /// Number of seeds contributed by this class.
    pub seed_count: usize,
    /// Number of expanded (post-dedup) items this class produced.
    pub expanded_count: usize,
    /// Number of items dropped during deduplication.
    pub dedup_drop_count: usize,
    /// Whether the class met its per-item floor.
    pub floor_satisfied: bool,
}

/// Full coverage report for a single corpus.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CoverageReport {
    /// Name of the corpus (matches the `--corpus` CLI argument).
    pub corpus_name: String,
    /// Total items produced after deduplication.
    pub total_items: usize,
    /// Per-class coverage keyed by class name.
    pub classes: BTreeMap<String, ClassCoverage>,
    /// IDs of seeds that produced zero expanded items after dedup.
    pub unexpanded_seed_slots: Vec<String>,
    /// Per-class parameter-space coverage ratio (observed / possible).
    pub parameter_space_coverage: BTreeMap<String, f64>,
}

// ---------------------------------------------------------------------------
// Core trait
// ---------------------------------------------------------------------------

/// The binding contract for every deterministic parameterized corpus generator
/// in the MAOS workspace.
///
/// # Determinism contract
///
/// Implementations MUST guarantee that `seed_corpus()` output combined with the
/// expansion rules (identified by `rule_version()`) produces byte-identical
/// `expand(n)` output on every host, every run.  See §Determinism in the
/// crate-level docs.
///
/// # Widening vs narrowing
///
/// Adding new trait methods (widening) is allowed by convention without an
/// architecture amendment.  Removing or renaming existing methods (narrowing)
/// requires invariant-lock review per ADR-037.
pub trait CorpusGenerator {
    /// The item type produced by `expand()`.
    type Item: serde::Serialize + serde::de::DeserializeOwned;

    /// The seed type returned by `seed_corpus()`.
    type Seed: serde::Serialize + serde::de::DeserializeOwned;

    /// Return the canonical set of seeds loaded from the pinned TOML file.
    fn seed_corpus(&self) -> Vec<Self::Seed>;

    /// Expand `n` items deterministically from the seed corpus.
    fn expand(&self, n: usize) -> Vec<Self::Item>;

    /// Validate a single expanded item.
    fn validate(&self, item: &Self::Item) -> ValidationOutcome;

    /// Compute a full coverage report from live generator state.
    fn coverage_report(&self) -> CoverageReport;

    /// SHA-256 hex of the canonical CBOR/JSONL serialization of
    /// `seed_corpus()`, combined with the expansion-rule version.
    fn seed_sha256(&self) -> String;

    /// Expansion-rule version string (e.g. `"v0.1"`).
    fn rule_version(&self) -> &'static str;
}
