// AUTO-GENERATED by /tmp/gen_sso_fixtures.py - DO NOT EDIT BY HAND.
//
// Offline RS256 OIDC fixtures (Story 11.4c AC1 tripwire; no network, no IdP).
//
// Two RSA-2048 keypairs: `keyA` is the trusted issuer key (present in JWKS_KEY_A);
// `keyB` is an attacker key (NOT in the JWKS). Every token is a real JWS:
//   - RS256 tokens are signed via `openssl dgst -sha256 -sign` (PKCS#1 v1.5);
//   - the HS256-confusion token is a real HMAC-SHA256 over the signing input
//     keyed by keyA's RSA *public-key* PEM (the classic alg-confusion vector).
// A REAL verifier must check the signature/alg/claims; a stubbed accept-all
// verifier would let the forged/confusion tokens through - exactly the canned-
// green trap the sso-fault-inject falsifier exists to catch (AC1, L4).

#![allow(dead_code)]

pub const JWKS_KEY_A: &str = "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"alg\":\"RS256\",\"kid\":\"key-a\",\"n\":\"vjNmtwbyyGrYVxgG-VYR7t3jGQyoENQy4O2vnTLm_oCW2H4CnnZ-J-m8_KuVMKLrPpNZkKAKz-y5MK_A7koqk-BcPgc9dhNRdaQVx5lwen-kdlQ9i83pPrLb3WEd449nvoQByrpLgT6pG6Sfz92Rg8rRADHmwj6-lCv5oZPDuuAVeKqSKCpNFeY3AcaLVAOtW9SUToHcqoFxw01E3WQoO-e87BW0MnprNVaJHjs3CX1_ybWtXpJ35zG1YTNNSm2nprF2CbZ0kpJ76b-SMgfFGM63i3r3NIPIXcgr-oCSviXO8wzXM4V6LTJBsT4IkzRmIWakHg09xvNnRl18qH5naQ\",\"e\":\"AQAB\"}]}";

pub const ISS_GOOD: &str = "https://idp.maos.example";
pub const ISS_BAD: &str = "https://attacker.example";
pub const AUD_EXPECTED: &str = "maos-deploy-alpha";
pub const PRINCIPAL_SUB: &str = "reza@maos.example";
pub const PRINCIPAL_NAME: &str = "Reza Cortex";
pub const EMAIL: &str = "reza@maos.example";

/// Correctly signed by keyA, live, right issuer/audience -> MUST verify.
pub const TOKEN_GOOD_RS256: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1hIn0.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vaWRwLm1hb3MuZXhhbXBsZSIsImF1ZCI6Im1hb3MtZGVwbG95LWFscGhhIiwiZXhwIjo5OTk5OTk5OTk5LCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.VHXFSPGqA9D0LgF-Vptn8ofmsvrpnZ37UgmGD71ovkBIJilKTEh56LV9RyKD5ozP4c-fJuXXU6EktjJJqw6OB-ZWUuMC7-PytpGqxLQAdk3CWbdo7DPTkG27AzEeJDrPpXfFwCpWO80OnTpX3L6sN3Y7q-JnrQuJBMWoBMCrUug2mhTEUEV-xh7lTC3T20j94tKGa7npheH-4sqe47KvkjL8UqjpHznb1_PExleMQ5qRdgWs5NSej_og0fmc8QkX6afNAOc0Nicj3BKCAvm5a7wVDQV8JJmvynquNy1_oGzw0vzJO5Kja0h43IKj0verJnWV_gvvKoRVnwKKREMZsw";
/// Same payload, signed by attacker keyB (not in JWKS) -> SignatureInvalid.
pub const TOKEN_WRONG_KEY: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1hIn0.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vaWRwLm1hb3MuZXhhbXBsZSIsImF1ZCI6Im1hb3MtZGVwbG95LWFscGhhIiwiZXhwIjo5OTk5OTk5OTk5LCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.Hi2Wd-wD9YGcO1Y0jskEk2YjaN9Qy4fjAD0184H4111hYsanx9AlBBwvseDTnkjdxtsRtmKsBTcowCC3sR8ykVbbDPFtiSjhxx669qAd9FDkHsAT6Fwy8aCMc_HSX1Yb7Hzj5wMAxJlp5_L0AE11UOzOl_6DKjsbYUd3uG-rjP731-Qbv3ulq_BVdpULDCQYiCGSSMSwHFjdc0oz2h1hSUUEeBInzGj2IEykNriUQj-lidyocAOHOawf6IojtHR8tBOMMwy78YHKyt4oiqF8vqL2vgCX0qwwI4_IfSIMQCSa1jpOVE5RTGXURFsfq1YFCnaXjw5tfgsQqiYepBhN_g";
/// alg:none header, empty signature -> AlgorithmRejected.
pub const TOKEN_ALG_NONE: &str = "eyJhbGciOiJub25lIiwidHlwIjoiSldUIiwia2lkIjoia2V5LWEifQ.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vaWRwLm1hb3MuZXhhbXBsZSIsImF1ZCI6Im1hb3MtZGVwbG95LWFscGhhIiwiZXhwIjo5OTk5OTk5OTk5LCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.";
/// alg:HS256 HMAC-confusion token (pubkey-as-HMAC-secret) -> AlgorithmRejected.
pub const TOKEN_HS256_CONFUSION: &str = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1hIn0.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vaWRwLm1hb3MuZXhhbXBsZSIsImF1ZCI6Im1hb3MtZGVwbG95LWFscGhhIiwiZXhwIjo5OTk5OTk5OTk5LCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.4zU2cm58OTCaGaqQOEjCif328DlQPWVu4Ha9Y5oWtNE";
/// Signed by keyA but exp=1 (1970) -> Expired.
pub const TOKEN_EXPIRED: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1hIn0.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vaWRwLm1hb3MuZXhhbXBsZSIsImF1ZCI6Im1hb3MtZGVwbG95LWFscGhhIiwiZXhwIjoxLCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.AyayVa6ceOSFvbGFYjKcktL485qegbF3RryxPjRX1MU87ChahxQCoyygbYyEWYhRk80hRRxn3H5_vnjkOs0sqE-Z7rv9CIZXjMdCakrXNCVN-MrLwcpbPF34puGen0rKRC6w4TA9Ax3IVXfDtE5BkvWeOgVckGd-tSnd6HDxYD-caapN75Gd7-BmRLBPzcUHWB_zk2AM_xOhV-JRHtl-qTTdxOowoVebcfEVbU_6XOsn-HbgqKfelUpyJ2iOE8OEgCNQBXmfxJ5-xbD5p-vwxG2j7bbSCH2W76zK8VmvDfMoomoJSVkeQRfdYrRVndaOvQsY081TPw9fSnQhuNdyBQ";
/// Signed by keyA but aud != this deployment -> AudienceMismatch.
pub const TOKEN_WRONG_AUD: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1hIn0.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vaWRwLm1hb3MuZXhhbXBsZSIsImF1ZCI6Im90aGVyLXJwIiwiZXhwIjo5OTk5OTk5OTk5LCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.S9uvtRTDXTfGKMeeJ66plhuUTyKwUVb1CMu_bptsoxtfG-bpKoBF6rMJNHNoZVxmz2DCvvFNYDXhqppsNhGhECggabKKJCcSnqrXcvNPO_vyAc7oin77S7COjiVrSGrTmtY76bt1xWJaZGvpGImf4jrLQX_zRkQhev-8nAxftGvT52jl0u942KUIt4SRdg2uX1B-ZhA9uovDpdI3aDiEKxjVxhTkamcw2IwyZ069VtRb84oNOG0uG-4VZM5ODkf-DzQbFVC7FKULgJ6Vu8ciI0bBCTsYn1jJKV5ZjqjI3DPl1zOl8OARJdGnbeViZiS-68w5XFBhJ12WVOaEwynQQQ";
/// Signed by keyA but iss not in trusted-issuer allowlist -> IssuerUntrusted.
pub const TOKEN_BAD_ISS: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1hIn0.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vYXR0YWNrZXIuZXhhbXBsZSIsImF1ZCI6Im1hb3MtZGVwbG95LWFscGhhIiwiZXhwIjo5OTk5OTk5OTk5LCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.cN56Ak8legCW9PO3lGS7gt94Anq5zg0bkhm1MltAALwt1OJ-msJh08GHakP52s3IRe3005G3Ub2mUKe9_U0Gr5xDE0hhfXGGSha_vsFVU3etDOezHAutBY_kOa7S13NZEn9zqDnmKM07H4_o2K0wmhVGnNBZvI-7odEQprC-5XR4Ai95-6xxmLO7ZuG40nT7gRd-Mm-5yUNIBQ9JpsXMWEexkkQ_Q6zUDMH03tvz9595FlPy1aIUqwTReqBA1e1AijgVUPkcDG9s6SPaQYm9M1yBRCLXYPntT3f0IkYADqhpubnPdcfPMo8sOXMZb-g89cyVXKTU9RVjYRJMoRvRMw";
/// Signed by keyA but kid not present in JWKS -> JwksUnavailable (fail-closed).
pub const TOKEN_UNKNOWN_KID: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1pc3Npbmcta2V5In0.eyJzdWIiOiJyZXphQG1hb3MuZXhhbXBsZSIsImlzcyI6Imh0dHBzOi8vaWRwLm1hb3MuZXhhbXBsZSIsImF1ZCI6Im1hb3MtZGVwbG95LWFscGhhIiwiZXhwIjo5OTk5OTk5OTk5LCJuYmYiOjAsImlhdCI6MTcwMDAwMDAwMCwibmFtZSI6IlJlemEgQ29ydGV4IiwiZW1haWwiOiJyZXphQG1hb3MuZXhhbXBsZSJ9.nB6TwUparjXILrgLEf2bBfDMASbnrtAsOs6DXg16EUZWIi5mU1ompq5nxYRKjE0S6j52D4ucyVlshsMFvoTGqITzIDzSa6-O-mGyxWjstiDWVnEjJq6fiW8pllgYZ_ff79wI33DKdXCtZI3rgTa6waNuOqmgLQ6UegyOUY-z8Oelv-x4AAXr_TDSEhmNs7iIsY98ic3hdXzgrFozVtHrO1Cnc-NoiNZ9nHonzh-l-FoOVdv3ZxHEjxtjlUE8ASTjT16HVU12U2diCTbIDqd-rAUD0IZEg7Rswe7OZk_YvCT_H3b2SAZH_q-y1ruf0AA6kiHewBIfouwMuvKwIM4htg";
